baseURL = "https://thorx2.github.io/gpportfolio/"
canonifyURLs = true
languageCode = "en-us"
title = "Gaudham"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]
page = [ "HTML", "RSS" ]

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blog"
weight = 1

[[Menus.main]]
identifier = "privacy"
name = "Privacy Policy"
title = "Privacy Policy"
url = "/privacy"
weight = 2

[params]
title = "Gaudham"
description = "A random game developer"
favicon = "/fav.png"
useBootstrapCDN = false
animate = true

  [params.font]
  fontSize = "1rem"
  fontWeight = 400
  lineHeight = 1.5
  textAlign = "left"

  [params.navbar]
  align = "ms-auto"
  brandName = "Gaudham"
  disableSearch = false

    [params.navbar.menus]
    disableAbout = false
    disableExperience = false
    disableEducation = false
    disableProjects = false
    disableAchievements = false
    disableContact = true

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Gaudham."
  subtitle = "I build games for mobile and PC"
  content = "A passionate game developer with close to 8 years of experience in the industry who loves making exciting and unique game mechanics and systems."
  image = "/images/me.png"

    [params.hero.bottomImage]
    enable = true

    [params.hero.button]
    enable = false
    name = "Resume"
    url = "#"
    download = true
    newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/thorx2"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://www.linkedin.com/in/gaudhamp/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-itch-io"
url = "https://thorx2.itch.io/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-google-play"
url = "https://play.google.com/store/apps/dev?id=5836476752700085717"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-gitlab"
url = "https://gitlab.com/thorx2"

  [params.about]
  enable = true
  title = "About Me"
#  image = "/images/me.png"
  content = """
I am a software developer with a passion for game development. I have a 8+ years of experience in the industry and have worked with various game engines, and have professional experience in both C++ as well as C#. I am currently working as a game programmer at Hypernova Interactive in Banglore KA, India

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = true
    title = "Here are a few technologies I've worked with:"
    items = [ "Unity 3D", "Unreal Engine 5", "Godot", "Coco2dx" ]

  [params.experience]
  enable = true

    [[params.experience.items]]
    job = "Game Programmer"
    company = "Hypernova Interactive"
    companyUrl = "https://www.hypernovainteractive.com/"
    date = "Jun 2020 - present"
    content = "I am currently working as a Gameplay programmer at Hypernova Interactive in Banglore, KA, India. I am part of the engineering team building the core foundational systems for Mayanagari, a 3rd person open world, mobile first cross platform action adventure game."

      [params.experience.items.featuredLink]
      enable = true
      name = "Company Website"
      url = "https://www.hypernovainteractive.com/"

    [[params.experience.items]]
    job = "Software Developer"
    company = "Longbow Games Pvt Ltd"
    companyUrl = "https://www.longbowgamesindia.in/"
    date = "Jun 2019 - May 2020"
    content = """
Worked closely with Wargaming Helsinki as well as Wargaming Berlin as both a tools programmer as well as a gameplay programmer. Built UI systems for War Tanks during its soft launch period. Later as a tools programmer for procedurally generating terrain meshes based of real world data from sources such as Google Maps for a RTS 4x game during it's prototype phase. 
"""

      [params.experience.items.featuredLink]
      enable = true
      name = "Company Website"
      url = "https://www.longbowgamesindia.in/"

      [params.experience.items.info]
      enable = true
      content = "I worked as a software developer as well as tools programmer at Longbow."

    [[params.experience.items]]
    job = "Game Programmer"
    company = "Ruby Seven Studios"
    companyUrl = "https://www.rubyseven.com/"
    date = "Feb 2015 - Jun 2019"
    content = """
Started my career in game development by making Social casino games built on top of a custom Coco2d-x SDK. UI element flow management such as sale, new game or announcement UI elements like popups where my forte. Specialized in the Android platform, debuging platform specific issues and various 3rd party SDK integration into the game.
"""

      [params.experience.items.info]
      enable = false

      [params.experience.items.featuredLink]
      enable = true
      name = "Company Website"
      url = "https://www.rubyseven.com/"

  [params.education]
  enable = true
  index = false

    [[params.education.items]]
    title = "Bachelor of Technology in Electronics and Commnucation"
    date = "2010 - 2014"
    GPA = "6.68 out of 10"
    content = ""

      [params.education.items.school]
      name = "Adi Shankara Institute of Engineering and Technology"

      [params.education.items.featuredLink]
      enable = false
      name = "My academic record"
      url = "https://example.com"

    [[params.education.items]]
    title = "High School"
#    GPA = "78% Overall Percentage"
    content = "Passed with a final percentage of 78% majoring in Computer Science."

      [params.education.items.school]
      name = "Bharatiya Vidya Bhavan."

      [params.education.items.featuredLink]
      enable = false
      url = "https://example.com"

  [params.achievements]
  enable = false

    [[params.achievements.items]]
    title = "Google kickstart runner"
    content = "I solved all problems with optimal solution."
    url = "https://example.com"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Facebook Hackathon Winner"
    content = "Developed a product using Artificial Intelligence."
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Hugo Profile"
    content = "Developed a theme and getting 1K+ downloads per month."
    url = "https://github.com/gurusabarish/hugo-profile"
    image = "/images/achievment.jpg"

    [[params.achievements.items]]
    title = "Microsoft Imagine Runner"
    content = "We are developed a product which can help others."

    [[params.achievements.items]]
    title = "Google Summer of Code"
    content = "Contributed to a open source project."
    url = "https://example.com"

  [params.projects]
  enable = true

    [[params.projects.items]]
    title = "Toon Tanks"
    content = """
    A simplistic 3D game built on Unreal Engine 5 with a mixture of C++ as well as Blueprint logic.    
    - Interop between C++ and Blueprints for UI and Game state management.
    - Simplistic "AI" systems for targets.
    - Core Gameplay elements such as Tank and Tower governed completely though C++ Code.
    """
    badges = [ "Unreal Engine 5", "C++", "Game Systems" ]

      [params.projects.items.featured]
      name = "Gitlab Link"
      link = "https://gitlab.com/thorx2/toon-tanks"

#      [[params.projects.items.links]]
#      icon = "fa fa-envelope"
#      url = "mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f"
#
#      [[params.projects.items.links]]
#      icon = "fab fa-github"
#      url = "https://github.com/gurusabarish/hugo-profile"
#
#      [[params.projects.items.links]]
#      icon = "fab fa-twitter"
#      url = "https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile"

    [[params.projects.items]]
    title = "Valiant Attempt"
    content = "A gameplay and game systems clone of ArcherIO, which I built as a machine test for a technical interview cycle."
#    image = "/images/projects/converter.jpg"
    badges = [ "Unity 3D", "Gameplay Systems", "Game Mechanics" ]

      [params.projects.items.featured]
      name = "Github Repo"
      link = "https://github.com/thorx2/valiant_attempt"

#      [[params.projects.items.links]]
#      icon = "fab fa-github"
#      url = "https://github.com/gurusabarish/converter"
#
#    [[params.projects.items]]
#    title = "Hugo Profile V2"
#    content = "A clean and simple Hugo template for personal portfolio and blog."
#    image = "/images/projects/profile2.jpg"
#    badges = [ "Hugo", "Bootstrap", "Javascript" ]
#
#      [params.projects.items.featured]
#      name = "Demo V2"
#      link = "https://hugo-profile-2.netlify.app"
#
#      [[params.projects.items.links]]
#      icon = "fab fa-github"
#      url = "https://github.com/gurusabarish/HugoProfileV2"

  [params.contact]
  enable = true
  content = "Reach out to me on my socials. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"

[params.footer.recentPosts]
path = "blog"
count = 3
title = "Recent Posts"
enable = false
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/thorx2"
linkedin = "https://www.linkedin.com/in/gaudhamp/"

  [params.listPages]
  disableFeaturedImage = false

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

  [params.terms]
  read = "Read"
  toc = "Table Of Contents"
  copyright = "All rights reserved"
  pageNotFound = "Page not found"
  emailText = "Check out this site"

  [params.datesFormat]
  article = "Jan 2, 2006"
  articleList = "Jan 2, 2006"
  articleRecent = "Jan 2, 2006"
